apiVersion: batch/v1
kind: Job
metadata:
  name: cassandra-script-runner
  annotations:
    "helm.sh/hook": post-install,post-upgrade
    "helm.sh/hook-weight": "5"
    "helm.sh/hook-delete-policy": hook-succeeded
spec:
  template:
    spec:
      containers:
      - name: cassandra-script-executor
        image: shrushti5/custom-cassandra:1.1
        command: ["/bin/bash", "-c"]
        args:
        - |
          cqlsh -u cassandra -p cassandra cassandra -f /usr/src/app/init.cql
      restartPolicy: Never
